// The Pages Function shipped to Cloudflare. Generated at build time with the
// role list and password hashes baked in. Validates session cookies, redirects
// to /login on a missing/expired cookie, and rewrites every request to the
// matching `_variants/<role>/` path before letting Pages serve it.

export interface AuthTemplateConfig {
  /** ordered low → high */
  roles: string[];
  /** role → encoded password hash ("iter:saltHex:hashHex"); only for roles above the default. */
  rolePasswords: Record<string, string>;
}

export function renderAuthMiddleware(cfg: AuthTemplateConfig): string {
  const rolesLiteral = JSON.stringify(cfg.roles);
  const passwordsLiteral = JSON.stringify(cfg.rolePasswords);

  return `// Auto-generated by the vaults CLI. Do not edit by hand.
// Roles, password hashes, and routing live here so the deployed Function
// is fully self-contained and doesn't need any other binding besides
// SESSION_SECRET (set via wrangler secret).

const ROLES = ${rolesLiteral};
const PASSWORDS = ${passwordsLiteral};
const COOKIE_NAME = "vault_role";
const COOKIE_MAX_AGE = 60 * 60 * 24 * 7; // 7 days
const PBKDF2_DEFAULT_ITERATIONS = 600000;

// ── Public middleware entry ────────────────────────────────────────────────

export const onRequest = async (ctx) => {
  const { request, env, next } = ctx;
  const url = new URL(request.url);

  // /login — POST validates a password and sets the session cookie; GET 404
  // is fine because /login.html is a static page.
  if (url.pathname === "/login" && request.method === "POST") {
    return handleLogin(request, env);
  }
  if (url.pathname === "/logout") {
    return new Response(null, {
      status: 302,
      headers: { Location: "/", "Set-Cookie": clearCookie() },
    });
  }

  // Skip rewriting for static-asset paths that don't have a per-role variant.
  // Anything outside the variant tree (images, css, login page, search index
  // for the default role on root, etc.) is served as-is by Pages.
  if (isSharedAsset(url.pathname)) return next();

  // Determine the user's role from the session cookie (default = lowest).
  const role = await readRole(request, env);

  // Rewrite to the matching variant. If the variant doesn't have this page,
  // a static 404 falls through.
  const target = "/_variants/" + role + url.pathname;
  const rewritten = new Request(new URL(target, url.origin).toString(), request);
  return env.ASSETS.fetch(rewritten);
};

// ── Login ─────────────────────────────────────────────────────────────────

async function handleLogin(request, env) {
  const form = await request.formData();
  const role = String(form.get("role") || "");
  const password = String(form.get("password") || "");
  const next = String(form.get("next") || "/");

  if (!ROLES.includes(role) || !PASSWORDS[role]) {
    return loginRedirect(next, "invalid_role");
  }

  const ok = await verifyPassword(password, PASSWORDS[role]);
  if (!ok) return loginRedirect(next, "wrong_password");

  const cookie = await signSessionCookie(role, env.SESSION_SECRET);
  return new Response(null, {
    status: 302,
    headers: { Location: next, "Set-Cookie": cookie },
  });
}

function loginRedirect(next, error) {
  const url = "/login.html?error=" + encodeURIComponent(error) + "&next=" + encodeURIComponent(next);
  return new Response(null, { status: 302, headers: { Location: url } });
}

// ── Cookie + role lookup ──────────────────────────────────────────────────

async function readRole(request, env) {
  const fallback = ROLES[0];
  const cookie = parseCookie(request.headers.get("Cookie") || "")[COOKIE_NAME];
  if (!cookie || !env.SESSION_SECRET) return fallback;
  const role = await verifySessionCookie(cookie, env.SESSION_SECRET);
  return role && ROLES.includes(role) ? role : fallback;
}

// Format: <role>.<expiryUnix>.<hmacHex>
async function signSessionCookie(role, secret) {
  const exp = Math.floor(Date.now() / 1000) + COOKIE_MAX_AGE;
  const payload = role + "." + exp;
  const sig = await hmac(payload, secret);
  return COOKIE_NAME + "=" + payload + "." + sig
    + "; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=" + COOKIE_MAX_AGE;
}

async function verifySessionCookie(cookie, secret) {
  const parts = cookie.split(".");
  if (parts.length !== 3) return null;
  const [role, expStr, sig] = parts;
  const exp = Number(expStr);
  if (!Number.isFinite(exp) || exp < Math.floor(Date.now() / 1000)) return null;
  const expected = await hmac(role + "." + expStr, secret);
  return constantTimeEqual(sig, expected) ? role : null;
}

function clearCookie() {
  return COOKIE_NAME + "=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0";
}

// ── Crypto primitives (Web Crypto API) ────────────────────────────────────

async function hmac(message, secretHex) {
  const keyBytes = fromHex(secretHex);
  const key = await crypto.subtle.importKey(
    "raw", keyBytes, { name: "HMAC", hash: "SHA-256" }, false, ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return toHex(new Uint8Array(sig));
}

async function verifyPassword(password, encoded) {
  const parts = encoded.split(":");
  if (parts.length !== 3) return false;
  const iterations = Number(parts[0]) || PBKDF2_DEFAULT_ITERATIONS;
  const salt = fromHex(parts[1]);
  const expected = fromHex(parts[2]);
  const key = await crypto.subtle.importKey(
    "raw", new TextEncoder().encode(password), { name: "PBKDF2" }, false, ["deriveBits"],
  );
  const bits = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt, hash: "SHA-256", iterations },
    key, expected.length * 8,
  );
  return constantTimeEqual(toHex(new Uint8Array(bits)), toHex(expected));
}

function constantTimeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

function toHex(bytes) {
  let s = "";
  for (let i = 0; i < bytes.length; i++) s += bytes[i].toString(16).padStart(2, "0");
  return s;
}

function fromHex(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function parseCookie(header) {
  const out = {};
  for (const part of header.split(/;\\s*/)) {
    const eq = part.indexOf("=");
    if (eq > 0) out[part.slice(0, eq)] = part.slice(eq + 1);
  }
  return out;
}

function isSharedAsset(pathname) {
  // Anything with an extension that's NOT html is a shared asset (images,
  // css, search-index json, preview json, etc.) and shouldn't be rewritten.
  // The wiki HTML uses extensionless paths.
  if (pathname === "/" || pathname.endsWith(".html")) return false;
  return /\\.[^/]+$/.test(pathname);
}
`;
}

export const LOGIN_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sign in</title>
<link rel="stylesheet" href="/styles.css">
<style>
  body { display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .login-card {
    max-width: 24rem; width: 90%; padding: 2rem;
    border: 1px solid var(--rule); border-radius: 6px; background: var(--bg);
  }
  .login-card h1 { margin: 0 0 1rem; font-size: 1.4rem; }
  .login-card label { display: block; font-size: 0.85rem; color: var(--muted); margin: 0.75rem 0 0.25rem; }
  .login-card select, .login-card input[type=password] {
    width: 100%; padding: 0.5rem 0.65rem; font: inherit; font-size: 0.95rem;
    background: var(--bg); color: var(--fg);
    border: 1px solid var(--rule); border-radius: 4px; outline: none;
  }
  .login-card select:focus, .login-card input:focus { border-color: var(--accent); box-shadow: 0 0 0 2px var(--wikilink-bg); }
  .login-card button {
    width: 100%; padding: 0.55rem 1rem; margin-top: 1rem; font: inherit;
    background: var(--accent); color: var(--accent-fg); border: 0; border-radius: 4px; cursor: pointer;
  }
  .login-error { color: #b94a3a; font-size: 0.85rem; margin: 0.75rem 0 0; }
</style>
</head>
<body>
<form class="login-card" method="POST" action="/login">
  <h1>Sign in</h1>
  <p id="err" class="login-error" hidden></p>
  <label for="role">Role</label>
  <select id="role" name="role">__ROLE_OPTIONS__</select>
  <label for="password">Password</label>
  <input id="password" type="password" name="password" autocomplete="current-password" required autofocus>
  <input type="hidden" name="next" id="next">
  <button type="submit">Sign in</button>
</form>
<script>
  const params = new URLSearchParams(location.search);
  const next = params.get("next") || "/";
  document.getElementById("next").value = next;
  const err = params.get("error");
  if (err) {
    const el = document.getElementById("err");
    el.textContent = err === "wrong_password" ? "Wrong password." : "Invalid role.";
    el.hidden = false;
  }
</script>
</body>
</html>`;
