// Pages Function for the MCP server. Reads from static assets via env.ASSETS
// — no R2 binding needed. Generated at build time so it ships alongside the
// auth middleware in dist/functions/.
//
// MCP tools (list_files, read_file, search_text, grep) operate on the .md
// source files we ship alongside the rendered .html. Role-aware: pulls the
// per-variant manifest matching the user's auth cookie.

export interface McpTemplateConfig {
  /** ordered low → high; first is the public default */
  roles: string[];
}

export function renderMcpFunction(cfg: McpTemplateConfig): string {
  const rolesLiteral = JSON.stringify(cfg.roles);

  return `// Auto-generated by the vaults CLI. Do not edit by hand.
const ROLES = ${rolesLiteral};
const COOKIE_NAME = "vault_role";
const PROTOCOL_VERSION = "2024-11-05";
const SERVER_INFO = { name: "vaults-template", version: "0.1.0" };

const TOOLS = [
  {
    name: "list_files",
    description: "List markdown files in the vault. Optionally filter by path prefix.",
    inputSchema: {
      type: "object",
      properties: { prefix: { type: "string" } },
    },
  },
  {
    name: "read_file",
    description: "Read the full text content of a single vault markdown file.",
    inputSchema: {
      type: "object",
      properties: { path: { type: "string" } },
      required: ["path"],
    },
  },
  {
    name: "search_text",
    description: "Plain substring search across vault markdown. Case-insensitive.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string" },
        prefix: { type: "string" },
        limit: { type: "number", default: 50 },
      },
      required: ["query"],
    },
  },
  {
    name: "grep",
    description: "Regex search across vault markdown. JavaScript regex syntax.",
    inputSchema: {
      type: "object",
      properties: {
        pattern: { type: "string" },
        flags: { type: "string", default: "" },
        prefix: { type: "string" },
        limit: { type: "number", default: 50 },
      },
      required: ["pattern"],
    },
  },
];

export const onRequestPost = async (ctx) => {
  const { request, env } = ctx;
  let req;
  try { req = await request.json(); } catch { return rpcError(null, -32700, "Parse error"); }
  if (req.jsonrpc !== "2.0" || typeof req.method !== "string") {
    return rpcError(req.id ?? null, -32600, "Invalid Request");
  }

  try {
    switch (req.method) {
      case "initialize":
        return rpcResult(req.id, {
          protocolVersion: PROTOCOL_VERSION,
          capabilities: { tools: {} },
          serverInfo: SERVER_INFO,
        });
      case "tools/list":
        return rpcResult(req.id, { tools: TOOLS });
      case "tools/call":
        return await handleToolCall(req, ctx);
      default:
        return rpcError(req.id, -32601, "Method not found: " + req.method);
    }
  } catch (err) {
    return rpcError(req.id, -32603, err instanceof Error ? err.message : "Internal error");
  }
};

async function handleToolCall(req, ctx) {
  const params = req.params ?? {};
  const args = params.arguments ?? {};

  // Determine which variant to read from based on the user's role cookie.
  const role = await readRole(ctx.request, ctx.env);
  const manifestUrl = new URL("/_variants/" + role + "/_manifest.json", ctx.request.url).toString();
  const manifestRes = await ctx.env.ASSETS.fetch(manifestUrl);
  let manifest;
  if (manifestRes.ok) {
    manifest = await manifestRes.json();
  } else {
    // Single-role build (no _variants prefix) — manifest sits at the root.
    const rootUrl = new URL("/_manifest.json", ctx.request.url).toString();
    const rootRes = await ctx.env.ASSETS.fetch(rootUrl);
    if (!rootRes.ok) return rpcError(req.id, -32603, "Manifest not found");
    manifest = await rootRes.json();
  }

  // The MCP tools work on .md sources only.
  const mdFiles = manifest.files.filter((f) => f.path.endsWith(".md"));

  switch (params.name) {
    case "list_files": {
      const prefix = String(args.prefix ?? "");
      const matched = prefix
        ? mdFiles.filter((f) => f.path.startsWith(prefix))
        : mdFiles;
      return toolResult(req.id, matched.map((f) => f.path + " (" + f.size + " bytes)").join("\\n"));
    }

    case "read_file": {
      const path = String(args.path ?? "");
      if (!path) return rpcError(req.id, -32602, "path is required");
      const exists = mdFiles.some((f) => f.path === path);
      if (!exists) return rpcError(req.id, -32602, "File not found: " + path);
      const fileUrl = new URL("/" + path, ctx.request.url).toString();
      const res = await ctx.env.ASSETS.fetch(fileUrl);
      if (!res.ok) return rpcError(req.id, -32603, "Read failed: " + path);
      return toolResult(req.id, await res.text());
    }

    case "search_text":
    case "grep": {
      const query = String(args.query ?? args.pattern ?? "");
      if (!query) return rpcError(req.id, -32602, (params.name === "grep" ? "pattern" : "query") + " is required");

      let matcher;
      if (params.name === "grep") {
        try { matcher = new RegExp(query, String(args.flags ?? "")); }
        catch (err) { return rpcError(req.id, -32602, "Invalid regex: " + (err instanceof Error ? err.message : "?")); }
      } else {
        const lc = query.toLowerCase();
        matcher = { test: (s) => s.toLowerCase().includes(lc) };
      }

      const prefix = String(args.prefix ?? "");
      const limit = Math.min(Number(args.limit ?? 50), 200);
      const candidates = prefix ? mdFiles.filter((f) => f.path.startsWith(prefix)) : mdFiles;

      const results = [];
      outer: for (const f of candidates) {
        const fileUrl = new URL("/" + f.path, ctx.request.url).toString();
        const res = await ctx.env.ASSETS.fetch(fileUrl);
        if (!res.ok) continue;
        const text = await res.text();
        const lines = text.split("\\n");
        for (let i = 0; i < lines.length; i++) {
          if (matcher.test(lines[i])) {
            const line = lines[i].trim();
            results.push(f.path + ":" + (i + 1) + ": " + (line.length > 200 ? line.slice(0, 200) + "…" : line));
            if (results.length >= limit) break outer;
          }
        }
      }
      return toolResult(req.id, results.length === 0 ? "No matches." : results.join("\\n"));
    }

    default:
      return rpcError(req.id, -32602, "Unknown tool: " + params.name);
  }
}

async function readRole(request, env) {
  const fallback = ROLES[0] ?? "public";
  if (!env.SESSION_SECRET) return fallback;

  // Authorization: Bearer <token> first (Foundry, MCP-over-HTTP clients).
  const auth = request.headers.get("Authorization") || "";
  const bearerMatch = /^Bearer\\s+(.+)$/i.exec(auth);
  if (bearerMatch) {
    const role = await verifyToken(bearerMatch[1], env.SESSION_SECRET);
    if (role && ROLES.includes(role)) return role;
  }

  // Then cookie (browser-based MCP clients, if any).
  const cookieHeader = request.headers.get("Cookie") || "";
  const cookies = {};
  for (const part of cookieHeader.split(/;\\s*/)) {
    const eq = part.indexOf("=");
    if (eq > 0) cookies[part.slice(0, eq)] = part.slice(eq + 1);
  }
  const cookie = cookies[COOKIE_NAME];
  if (!cookie) return fallback;
  const role = await verifyToken(cookie, env.SESSION_SECRET);
  return role && ROLES.includes(role) ? role : fallback;
}

async function verifyToken(token, secretHex) {
  const parts = token.split(".");
  if (parts.length !== 3) return null;
  const [role, expStr, sig] = parts;
  const exp = Number(expStr);
  if (!Number.isFinite(exp) || exp < Math.floor(Date.now() / 1000)) return null;
  const keyBytes = new Uint8Array(secretHex.length / 2);
  for (let i = 0; i < keyBytes.length; i++) keyBytes[i] = parseInt(secretHex.slice(i * 2, i * 2 + 2), 16);
  const key = await crypto.subtle.importKey("raw", keyBytes, { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const macBytes = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(role + "." + expStr));
  let macHex = "";
  for (const b of new Uint8Array(macBytes)) macHex += b.toString(16).padStart(2, "0");
  if (macHex.length !== sig.length) return null;
  let diff = 0;
  for (let i = 0; i < macHex.length; i++) diff |= macHex.charCodeAt(i) ^ sig.charCodeAt(i);
  return diff === 0 ? role : null;
}

function rpcResult(id, result) {
  return new Response(JSON.stringify({ jsonrpc: "2.0", id, result }), {
    headers: { "Content-Type": "application/json" },
  });
}
function rpcError(id, code, message) {
  return new Response(JSON.stringify({ jsonrpc: "2.0", id, error: { code, message } }), {
    headers: { "Content-Type": "application/json" },
  });
}
function toolResult(id, text) {
  return rpcResult(id, { content: [{ type: "text", text }] });
}
`;
}
